CREATE FUNCTION gerarExtrato(@ID_USUARIO INT)
RETURNS TABLE
AS
RETURN (
    SELECT
        HISTORICOTRANSACOES.NUM_CONTA,
        HISTORICOTRANSACOES.ID_TRANSACAO,
        TRANSACAO.dt_hr_transacao,
        Conta.saldo
    FROM
        USUARIO
        INNER JOIN CONTA ON CONTA.USUARIO_ID = USUARIO.ID_USUARIO
        INNER JOIN HISTORICOTRANSACOES ON HISTORICOTRANSACOES.NUM_CONTA = CONTA.NUM_CONTA
        INNER JOIN TRANSACAO ON TRANSACAO.ID_TRANSACAO = HISTORICOTRANSACOES.ID_TRANSACAO
    WHERE
        USUARIO.ID_USUARIO = @ID_USUARIO
);

drop function gerarExtrato